---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: adservice
  namespace: production
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    flux.weave.works/tag.chart-image: glob:master-*
spec:
  releaseName: adservice
  helmVersion: v3
  chart:
    git: git@gitlab.com:express42/kubernetes-platform-demo/microservices-demo.git
    ref: master
    path: deploy/charts/adservice
  values:
    image:
      repository: avtandilko/adservice
      tag: master-d6f043c89561f25e0745c37eb7ecf05e1ee443c7
