---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: cartservice
  namespace: production
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    flux.weave.works/tag.chart-image: glob:master-*
spec:
  releaseName: cartservice
  helmVersion: v3
  chart:
    git: git@gitlab.com:express42/kubernetes-platform-demo/microservices-demo.git
    ref: master
    path: deploy/charts/cartservice
  values:
    image:
      repository: avtandilko/cartservice
      tag: master-04a71a24e2b4b48d2b8122571187d796f69ec6cc
