apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus-pods-access
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-pods-access-binding
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: ClusterRole
  name: prometheus-pods-access
subjects:
- kind: Group
  name: system:serviceaccounts:prometheus
  namespace: prometheus