apiVersion: apps/v1
kind: Deployment
metadata:
 name: web 
spec:
 replicas: 3
 selector: 
  matchLabels: 
    app: web 
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxUnavailable: 0
   maxSurge: 100%
 template:
  metadata:
    name: web
    labels: 
      app: web
  spec:
    initContainers:
    - name: init-webpod
      image: busybox:1.36
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
      - name: app
        mountPath: /app
      resources:
        limits:
          cpu: "0.5"
          memory: "32Mi"
        requests:
          cpu: "0.1"
          memory: "16Mi"
    containers: 
    - name: webpod
      image: m1keio/web:v0.1
      volumeMounts:
      - name: app
        mountPath: /app
      resources:
        limits:
          cpu: "0.5"
          memory: "32Mi"
        requests:
          cpu: "0.1"
          memory: "16Mi"
      readinessProbe: 
        httpGet:
          path: /index.html
          port: 8000
      livenessProbe:
        tcpSocket: 
          port: 8000
    volumes:
      - name: app
        emptyDir: {}